name: CD

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  cd:
    name: CD Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run CD
        run: |
          echo "CD pipeline completed successfully."
